# Generated by Django 2.1.5 on 2019-03-28 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
                ('profile_dp', models.ImageField(upload_to='static/images', verbose_name='Profile Picture')),
                ('profile_created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('experience', models.IntegerField(null=True)),
                ('previous_projects', models.TextField(blank=True, null=True)),
                ('Area_of_Interest', models.CharField(default='Python', max_length=200)),
                ('city', models.TextField(default='Batala Road,Amritsar,India')),
                ('Something_about_yourself', models.TextField(default='NA')),
                ('user_type', models.CharField(choices=[('D', 'Developer'), ('R', 'Recruiter'), ('B', 'Both')], default='D', max_length=2, verbose_name='Type of profile')),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Profile's",
            },
        ),
    ]
