# Generated by Django 2.1.5 on 2019-04-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_dp',
            field=models.ImageField(default='static/images/tenor.gif', upload_to='static/images', verbose_name='Profile Picture'),
        ),
    ]
