# Generated by Django 2.1.5 on 2019-03-28 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, verbose_name='Project Name')),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('CAN', 'CANCELLED'), ('COM', 'COMPLETED'), ('ACC', 'ACCEPTED')], default='PEN', max_length=3)),
                ('project_details', models.TextField(verbose_name='Complete Decription about Project')),
                ('skills', models.CharField(max_length=10)),
                ('budget', models.TextField(verbose_name='Enter your budget')),
                ('time_frame', models.TextField(verbose_name='Required Working Hours')),
                ('by_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Projects's",
            },
        ),
    ]
