# Generated by Django 2.1.5 on 2019-03-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_has_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='has_exam',
            field=models.CharField(choices=[('NO', 'NO'), ('YS', 'YES')], default='NO', max_length=2),
        ),
    ]
