# Generated by Django 2.1.5 on 2019-03-28 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
        ('questions', '0001_initial'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('by_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='by_username', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.Exam')),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='marks.Marks')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='questions.Questions')),
            ],
        ),
    ]
