# Generated by Django 2.1.5 on 2019-03-28 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionanswer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
