# Generated by Django 2.1.5 on 2019-03-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionanswer', '0002_auto_20190328_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='marks.Marks'),
        ),
    ]
