# Generated by Django 2.1.5 on 2019-03-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionanswer', '0003_auto_20190328_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.Exam'),
        ),
    ]
