# Generated by Django 2.1.5 on 2019-03-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
                ('option_1', models.CharField(max_length=50)),
                ('option_2', models.CharField(max_length=50)),
                ('option_3', models.CharField(max_length=50)),
                ('option_4', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(choices=[('O1', 'option_1'), ('O2', 'option_2'), ('O3', 'option_3'), ('O4', 'option_4')], max_length=2)),
                ('Question_weightage', models.IntegerField(help_text='Weightage should be marks to given for Correct Answer', verbose_name='Enter Weightage for Question')),
            ],
        ),
    ]
