# Generated by Django 2.1.5 on 2019-03-28 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_scored', models.IntegerField(verbose_name='Marks Scored')),
                ('by_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Marks_by_user', to=settings.AUTH_USER_MODEL)),
                ('on_project', models.OneToOneField(on_delete='Nothing', related_name='on_project', to='projects.projects')),
            ],
        ),
    ]
