# Generated by Django 2.1.5 on 2019-03-28 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marks_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marks',
            name='on_project',
            field=models.ForeignKey(on_delete='Nothing', related_name='on_project', to='projects.projects'),
        ),
    ]
