# Generated by Django 2.1.5 on 2019-03-28 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('by_user', models.ForeignKey(on_delete='models.cascade', related_name='by_user', to=settings.AUTH_USER_MODEL)),
                ('on_user', models.ForeignKey(on_delete='Models.Cascade', related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
