# Generated by Django 2.1.5 on 2019-03-28 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Done on')),
                ('amount', models.IntegerField(verbose_name='Amount Transferred')),
                ('from_user', models.OneToOneField(on_delete='None', related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('of_wallet', models.ForeignKey(on_delete='models.CASCADE', related_name='transactions', to='wallet.Wallet')),
                ('to_user', models.OneToOneField(on_delete='None', related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
