# Generated by Django 2.1.5 on 2019-03-28 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField(verbose_name='Bid Amount')),
                ('by_user', models.ForeignKey(on_delete='models.CASCADE', related_name='bid_by_user', to=settings.AUTH_USER_MODEL)),
                ('on_project', models.ForeignKey(on_delete='models.CASCADE', related_name='Bids', to='projects.projects')),
            ],
        ),
    ]
