# Generated by Django 2.1.5 on 2019-04-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
