# Generated by Django 2.1.5 on 2019-04-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0002_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='by_user',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='bid_by_user', to='profiles.profiles'),
        ),
    ]
